name: attributeanalysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3 
  - pytorch==1.11.0 
  - torchvision==0.12.0 
  - numpy
  - pillow
  - pandas
  - tqdm
  - pip
  - pip:
    - torch-clip==0.1.0